### ISSUE TITLE
WorldStabilizer and Hangar issue

### ISSUE THREAD

**Issue by bcqJC** [whale2/WorldStabilizer#1] opened 2019-07-23 19:01 UTC
Hi! You requested a save file of my WorldStabilizer and Hangar issue.

I'm attaching a ZIP file. The ship in the save that uses the upside down Ground Hangar is Agila.
[sci_snacks_2.zip](https://github.com/whale2/WorldStabilizer/files/3423589/sci_snacks_2.zip)

**Comment by whale2** [comment] 2019-07-29 18:10
@bcqJC 
Tried with smaller rover - seems fine.
https://www.youtube.com/watch?v=etAI9NqNnVs&feature=youtu.be

What was the one you had issues with?

**Comment by whale2** [comment] 2019-07-29 22:02
Sorry, disregard that. Reproduced and found the reason. The fix is another matter...

**Comment by whale2** [comment] 2019-07-29 23:55
@bcqJC , please try this .dll
https://github.com/whale2/WorldStabilizer/blob/master/GameData/WorldStabilizer/Plugins/WorldStabilizer.dll

**Comment by bcqJC** [comment] 2019-07-30 04:32
@whale2, I just tried the fix. It's a good news, bad news thing. 

Good news... It fixed the issue between WorldStabilizer and Hangar. 

Bad news... It broke the existing "feature" where WorldStabilizer fixes the issue with OPT "Humpback" Class Tail Cargo Ramp (OPT_Legacy/Parts/Humpback/OPT_l_7m_cargoTail/l_7m_cargoTail). The issue with that part is when it's used, the vessel spawns a few kilometers above the runway. Somehow, using WorldStabilizer with the OPT_Legacy mod fixes that issue.

So between the 2 issues, if you have to choose, just leave the existing code that fixes the OPT_Legacy issue. I imagine that that affects more people.

Thanks for looking into it. I don't mind if you close this issue since I have the existing workaround of using the Hangar part upside-down.

**Comment by whale2** [comment] 2019-07-30 10:57
No, that should be fixable. Thanks for the report. I'll post here fixed .dll again.

**Comment by whale2** [comment] 2019-07-31 20:25
@bcqJC 
Was rather dumb mistake, please refresh the link and try again. Works for me.

**Comment by bcqJC** [comment] 2019-07-31 22:20
It works!  There was some wierd behaviour initially though. 

Attempt #1: Selected test vessel from SPH and edited the vessel so that Ground Hangar is upright, then launched the vessel. 
The vessel spawned a few meters - I failed to note how many - and hit the runway hard but upright. It bounced for a bit then settled down. 
Launched the payload from the Ground Hangar. It did not fall through. I reverted back to SPH to re-launch to find out how many meters above the runway it spawned.

Attempt #2: Was watching this time. Vessel spawned 2 meters above runway (75 meters), hit the runway gently, bounced a little then settled (73 meters). The bounce was gentler this time. Can only conclude that attempt #1 spawned higher than 2 meters.
Launched the payload without issues. Reverted back to SPH.

Attempt #3: Again watching. This time, the vessel spawned less than a meter above ground, I'd even say almost touching the runway. Very slight bounce and everything settled down quickly.
Launched the payload without issues. Reverted back to SPH.

I did a few more attempts. Same results as attempt #3. Shut down KSP and started back up again. Maybe it's like that issue with EVE/SVE/SVT where things don't line up initially but changing scenes fixes it. Did the same things as before but I can't recreate the results from attempts #1 and #2. It's like something got fixed in the Persistence file. So I tried to load an old quicksave. Still can't recreate the initial results.

So aside from that surprise at the start, I agree it's fixed.

**Comment by whale2** [comment] 2019-07-31 22:28
That's strange, it should not be 2 meters above. Can you please attach the log file?

**Comment by bcqJC** [comment] 2019-07-31 23:37
Most recent log file attached. I forgot to save the initial log and have since restarted KSP, as I mentioned above. 

I cannot recreate that issue anymore. After the 3rd test, the vessel now spawns at ground level, no bouncing around. The issue is gone.

**Comment by bcqJC** [comment] 2019-07-31 23:38
[KSP_log.zip](https://github.com/whale2/WorldStabilizer/files/3454273/KSP_log.zip)

**Comment by whale2** [comment] 2019-07-31 23:54
Hmm, log says the vessel is launched very high, as it is always happens to OPT stuff, but then it has been moved down and left alone when distance between small gear and runway was 0.09 m.

I'd ask once again to strip the ship from any unneeded parts (expansion, fuel balancer, etc.) and attach a craft file.

**Comment by bcqJC** [comment] 2019-07-31 23:58
BTW, I realized that I have VSS on and use wbadmin backups. So I have an image of my saves as of last night (I do nightly backups). I restored and did the same tests again and now have the logs showing that the initial spawns we're high and subsequent spawns were lower.

[KSP_2_log.zip](https://github.com/whale2/WorldStabilizer/files/3454302/KSP_2_log.zip)

**Comment by whale2** [comment] 2019-08-01 00:51
Hmm. Not sure if it is OPT-specific, but it might be. 
You can try tweaking config a little bit. It is located in GameData/WorldStabilizer/WorldStabilizer.cfg

Try changing lastResortAltitude from 2 to 0.5

**Comment by bcqJC** [comment] 2019-08-01 00:53
Here are the stripped down craft files. "Agila X" is the carrier. "Jeep X" is the payload. Mods are Hangar, OPT (OPT, OPT_Legacy, OPT_Reconfig), and WorldStabilizer.

[Ships.zip](https://github.com/whale2/WorldStabilizer/files/3454425/Ships.zip)

**Comment by bcqJC** [comment] 2019-08-02 01:59
After lots of tests, I found out why the vessel starts +2 meters above the runway. No need to change the CFG entries.

The vessel starts +2 meters above the runway if I didn't click Save (in SPH) before clicking Launch. That's it!

Attached below are the logs. The first is with the CFG changed. I was trying out different values and testing when I realized that the instances where vessel started at the correct altitude were the times when I clicked Save before Launching.

The second log is when I restored the CFG to the default settings. Then I tried testing the "Save before Launch" pattern. It worked!

I think you can release the fix with the caveat that users should click "Save" before clicking "Launch" in the Editor. 

[KSP_log_WS_cfg_changed.zip](https://github.com/whale2/WorldStabilizer/files/3459314/KSP_log_WS_cfg_changed.zip)
[KSP_log_default_cfg.zip](https://github.com/whale2/WorldStabilizer/files/3459313/KSP_log_default_cfg.zip)

**Comment by whale2** [comment] 2019-08-08 10:43
Fixed in 0.9.5

**Closed as completed by whale2** 2019-08-08 10:43 UTC
